using System;
using Slb.Ocean.Core;
using Slb.Ocean.Data.Hosting;
using Slb.Ocean.Petrel.Data;
using Slb.Ocean.Petrel.Data.Persistence;

namespace MultipleSave
{
    /// 
    /// [quarta-feira, 18 de fevereiro de 2026] Generated by SLB Ocean Data Source Wizard
    /// 
    /// Author   : diogosctn
    /// 
    /// <summary>
    /// Factory for custom data sources. 
    /// For each Petrel project, Petrel will ask the registered factories to return the (non serializable) custom data source. 
    /// A data source returned should not be added to the data source manager by the plug-in (it will be added automatically). 
    /// </summary>
    public class DataSourceTextFactory : DataSourceFactory
    {
        private static DataSourceTextFactory _instance;
        private static string DataSourceId = "{D1A6248E-9CBF-4085-838C-F2F5217E5DA8}";

        private DataSourceTextFactory()
        {
        }

        public static DataSourceTextFactory Instance
        {
            get { return _instance ?? (_instance = new DataSourceTextFactory()); }
        }

        /// <summary>
        /// Gets the data source with corresponding source Id.
        /// </summary>
        public static StructuredArchiveDataSource Get(IDataSourceManager dataSourceManager)
        {
            return dataSourceManager.GetSource(DataSourceId) as StructuredArchiveDataSource;
        }

        /// <summary>
        /// Gets the data source that uses StructuredArchive serialization. 
        /// Data stored in StructuredArchiveDataSource is only saved if IsDirty is true. 
        /// The flag is automatically set to true if a new object is added to the datasource, but plug-ins are responsible to set IsDirty on any change in the domain object data which must be serialized. 
        /// </summary>
        public override IDataSource GetDataSource()
        {
            //Add custom domain object types into this array
            Type[] supportedTypes = new Type[] { typeof(MultipleSave.CustomDomainObjectText) };
            StructuredArchiveDataSource dataSource = new StructuredArchiveDataSource(DataSourceId, supportedTypes);
            //Register archivable surrogates here
            //dataSource.AddArchivableSurrogate(new DataSourceTextFacadeSurrogate<Borehole>());
            return dataSource;
        }
    }

    /// <summary>
    /// Surrogate for native domain objects.
    /// </summary>
    /// <typeparam name="T"></typeparam>    
    public class DataSourceTextFacadeSurrogate<T> : ArchivableSurrogate<T> where T : class, IIdentifiable, IDomainObject
    {
        protected override T Serialize(IStructuredArchive ar, T value)
        {
            ar.SerializeReference("Droid", () => value.Droid, (droid) => CoreSystem.GetService<IDomainObjectHost>().Admin.ToIdentifiableFacade<T>(droid));
            return value;
        }
    }
}